# Generated by Django 6.0.7 on 2026-07-14 02:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cuentas.organizacion', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='código de barras')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('libra', 'Libra'), ('arroba', 'Arroba'), ('litro', 'Litro'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('servicio', 'Servicio')], default='unidad', max_length=20)),
                ('es_servicio', models.BooleanField(default=False, verbose_name='es servicio')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('precio_venta_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='precio de venta mínimo')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('precio_compra_maximo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='precio de compra máximo')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=Decimal('13'), help_text='Porcentaje de IVA. En Bolivia, 13% por defecto.', max_digits=5, verbose_name='impuesto (%)')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria', verbose_name='categoría')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cuentas.organizacion', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('venta', 'Precio de venta'), ('venta_minimo', 'Precio de venta mínimo'), ('compra', 'Precio de compra'), ('compra_maximo', 'Precio de compra máximo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cuentas.organizacion', verbose_name='organización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'historial de precio',
                'verbose_name_plural': 'historial de precios',
                'db_table': 'historial_precio',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('organizacion', 'nombre'), name='categoria_nombre_unico_por_org'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['organizacion', 'codigo_barras'], name='producto_organiz_56ef03_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('organizacion', 'sku'), name='producto_sku_unico_por_org'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras', ''), _negated=True), fields=('organizacion', 'codigo_barras'), name='producto_codigobarras_unico_por_org'),
        ),
        migrations.AddIndex(
            model_name='historialprecio',
            index=models.Index(fields=['producto', 'tipo', '-creado_en'], name='historial_p_product_a3d517_idx'),
        ),
    ]
