# Generated by Django 6.0.7 on 2026-07-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_token_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='bajo_minimo',
            field=models.BooleanField(default=False, verbose_name='autorizada bajo el precio mínimo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='bajo_minimo',
            field=models.BooleanField(default=False, verbose_name='autorizada bajo el precio mínimo'),
        ),
    ]
