# Generated by Django 6.0.7 on 2026-07-14 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nit_ci', models.CharField(blank=True, max_length=30, verbose_name='NIT/CI')),
                ('es_cliente', models.BooleanField(default=False, verbose_name='es cliente')),
                ('es_proveedor', models.BooleanField(default=False, verbose_name='es proveedor')),
                ('es_transportadora', models.BooleanField(default=False, verbose_name='es transportadora')),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cuentas.organizacion', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'tercero',
                'verbose_name_plural': 'terceros',
                'db_table': 'tercero',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContactoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('telefono', 'Teléfono'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='telefono', max_length=20)),
                ('valor', models.CharField(max_length=150)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cuentas.organizacion', verbose_name='organización')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'db_table': 'contacto_tercero',
            },
        ),
        migrations.CreateModel(
            name='UbicacionTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cuentas.organizacion', verbose_name='organización')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'db_table': 'ubicacion_tercero',
            },
        ),
        migrations.AddIndex(
            model_name='tercero',
            index=models.Index(fields=['organizacion', 'nombre'], name='tercero_organiz_08f327_idx'),
        ),
    ]
