# Generated by Django 6.0.7 on 2026-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('login_fallido', 'Inicio de sesión fallido')], max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('objeto_desc', models.CharField(blank=True, max_length=255, verbose_name='descripción del objeto')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bitácora',
                'verbose_name_plural': 'bitácoras',
                'db_table': 'bitacora',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'detalle de bitácora',
                'verbose_name_plural': 'detalles de bitácora',
                'db_table': 'bitacora_detalle',
            },
        ),
    ]
