# Generated by Django 6.0.7 on 2026-07-13 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='cuentas.organizacion', verbose_name='organización'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bitacoradetalle',
            name='bitacora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='auditoria.bitacora'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['organizacion', '-fecha'], name='bitacora_organiz_3022d4_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['modelo', 'objeto_id'], name='bitacora_modelo_095c69_idx'),
        ),
    ]
